apiVersion: apps/v1
kind: Deployment
metadata:
  name: criarcontato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: criarcontato
  template:
    metadata:
      labels:
        app: criarcontato
    spec:
      containers:
        - name: criarcontato
          image: leonardodfg12/criarcontato:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver;Database=ContactZone;User Id=sa;Password=@Sql2019;MultipleActiveResultSets=true;Encrypt=YES;TrustServerCertificate=YES"
            - name: RABBITMQ_HOST
              value: "rabbitmq://rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: criarcontato
spec:
  selector:
    app: criarcontato
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
